export const products = [
  {
    id: 'chicken-crunch',
    name: 'Chicken Crunch',
    category: 'Chicken',
    price: 18,
    rating: 4.9,
    badge: 'Hot',
    image: '/assets/wings.webp',
    description: 'Peppery crisp wings, cultured dip and bright garden herbs.',
  },
  {
    id: 'deep-dish',
    name: 'Chicago Deep Dish',
    category: 'Pizza',
    price: 22,
    rating: 4.8,
    badge: 'Popular',
    image: '/assets/pizza.webp',
    description: 'Slow tomato, bubbling cheese and a golden hand-stretched crust.',
  },
  {
    id: 'cheese-pull',
    name: 'Cheese Pull Supreme',
    category: 'Pizza',
    price: 24,
    rating: 4.9,
    badge: 'Chef pick',
    image: '/assets/cheese-pizza.webp',
    description: 'Charred edges, basil and an unapologetically generous cheese pull.',
  },
  {
    id: 'firehouse-burger',
    name: 'Firehouse Burger',
    category: 'Burgers',
    price: 17,
    rating: 4.7,
    badge: 'New',
    image: '/assets/burger.webp',
    description: 'Double-seared beef, crunchy greens and our smoky house sauce.',
  },
  {
    id: 'smash-stack',
    name: 'Smash Stack & Fries',
    category: 'Burgers',
    price: 21,
    rating: 4.9,
    badge: 'Best seller',
    image: '/assets/burger-fries.webp',
    description: 'Two lace-edged patties, molten cheddar and rosemary fries.',
  },
  {
    id: 'garden-tacos',
    name: 'Garden Street Tacos',
    category: 'Fresh',
    price: 16,
    rating: 4.6,
    badge: 'Fresh',
    image: '/assets/tacos.webp',
    description: 'Roasted vegetables, lime crema and a shower of fresh coriander.',
  },
  {
    id: 'flame-grilled',
    name: 'Flame Grilled Plate',
    category: 'Grill',
    price: 27,
    rating: 4.8,
    badge: 'Signature',
    image: '/assets/grilled-chicken.webp',
    description: 'Fire-grilled chicken, pan jus and market vegetables.',
  },
  {
    id: 'silk-road-pasta',
    name: 'Silk Road Pasta',
    category: 'Pasta',
    price: 20,
    rating: 4.7,
    badge: 'Seasonal',
    image: '/assets/pasta.webp',
    description: 'Silky ribbons, toasted spice butter and parmesan snow.',
  },
]

const sharedFeatures = [
  ['Made to order', 'Every plate leaves the pass bright, hot and generous.'],
  ['Local first', 'Season-led ingredients from producers we know by name.'],
  ['Fast delivery', 'Carefully packed and on its way in thirty minutes.'],
]

export const screenDefinitions = {
  'home-1': {
    key: 'home-1',
    frame: 'Home-1',
    path: '/home-1',
    layout: 'dark-table',
    theme: {
      accent: '#ffc526',
      accent2: '#f43142',
      surface: '#fff9ed',
      ink: '#171717',
      hero: '#111315',
      heroText: '#ffffff',
      card: '#ffffff',
    },
    eyebrow: 'Welcome to TasteNest',
    title: 'The Perfect Space to Enjoy Fantastic Food',
    lead: 'A table built for long conversations, bright seasonal plates and the easy ritual of sharing something exceptional.',
    price: '$18',
    primary: 'See Our Menu',
    secondary: 'Watch video',
    heroImage: '/assets/food-table.webp',
    heroAlt: 'A generous table filled with colourful shared dishes',
    alternate: {
      eyebrow: 'Friday fire drop',
      title: 'Flame grilled. Full flavour.',
      lead: 'A generous grill plate with smoky edges and bright sides.',
      price: '$27',
      image: '/assets/grilled-chicken.webp',
      alt: 'Flame-grilled chicken plate',
    },
    story: {
      eyebrow: 'Our secret is patience',
      title: 'Marinated slow. Fried fast.',
      body: 'A full day in our pepper-bright marinade, a light double dredge and a short trip through clean hot oil. That is the whole trick.',
      image: '/assets/grilled-chicken.webp',
      alt: 'Freshly grilled chicken ready to serve',
      stats: [['24h', 'marinade'], ['11', 'house spices'], ['08m', 'to your table']],
    },
    featureTitle: 'Popular food items',
    featured: ['chicken-crunch', 'firehouse-burger', 'deep-dish', 'smash-stack'],
    features: sharedFeatures,
    quote: 'A proper crunch, a proper kick, and somehow still light enough to order another round.',
    author: 'Piter Bowman',
  },
  'home-2': {
    key: 'home-2',
    frame: 'Home-2',
    path: '/home-2',
    layout: 'airy-collage',
    theme: {
      accent: '#f42d4e',
      accent2: '#ffd238',
      surface: '#ffffff',
      ink: '#171315',
      hero: '#ffffff',
      heroText: '#171315',
      card: '#ffffff',
    },
    eyebrow: 'Arriving From Paris In 1984',
    title: 'Best Food for Best Restaurants',
    lead: 'A bright Parisian-inspired booking page with playful yellow geometry, generous plates and a table waiting for you.',
    price: '$16',
    primary: 'Reserve a Table',
    secondary: 'Explore Menu',
    heroImage: '/assets/pasta.webp',
    heroAlt: 'A colourful plated pasta dish',
    alternate: {
      eyebrow: 'This weekend only',
      title: 'The stack everyone talks about.',
      lead: 'Double-seared patties and a tray of crisp rosemary fries.',
      price: '$21',
      image: '/assets/burger-fries.webp',
      alt: 'Double burger served with fries',
    },
    story: {
      eyebrow: 'About our food',
      title: 'The best delicious food made from us.',
      body: 'Comfort food can still be thoughtful. We source well, season with intention and never let a plate wait under the lamp.',
      image: '/assets/cheese-pizza.webp',
      alt: 'Cheese pizza being served hot',
      stats: [['250+', 'happy guests'], ['153+', 'menu ideas'], ['25+', 'awards']],
    },
    featureTitle: 'Hot delicious items',
    featured: ['deep-dish', 'chicken-crunch', 'firehouse-burger', 'garden-tacos'],
    features: sharedFeatures,
    quote: 'The room is fun, the service moves and the burger arrives exactly as outrageous as the picture.',
    author: 'Amelia Emily',
  },
  'home-3': {
    key: 'home-3',
    frame: 'Home-3',
    path: '/home-3',
    layout: 'kings-burger',
    theme: {
      accent: '#f52d50',
      accent2: '#f5c52c',
      surface: '#fff4f5',
      ink: '#171317',
      hero: '#121216',
      heroText: '#ffffff',
      card: '#ffffff',
    },
    eyebrow: '20% Off on your first order',
    title: 'Kings Burger',
    lead: 'An after-dark burger page with a black stage, a coral split, oversized food and loud, delicious confidence.',
    price: '$17',
    primary: 'View Our Menu',
    secondary: 'How we work',
    heroImage: '/assets/burger.webp',
    heroAlt: 'A tall, freshly made burger',
    alternate: {
      eyebrow: 'Cheese, please',
      title: 'Pull apart the perfect slice.',
      lead: 'Basil, blistered tomato and our signature mozzarella blend.',
      price: '$24',
      image: '/assets/cheese-pizza.webp',
      alt: 'Cheese pizza with a dramatic cheese pull',
    },
    story: {
      eyebrow: 'Learn from Foodking',
      title: 'A neighbourhood pizzeria with a playful streak.',
      body: 'Every dough rests for forty-eight hours before meeting a fiercely hot stone. The result is crisp, chewy and made for sharing.',
      image: '/assets/chef.webp',
      alt: 'Chef presenting a finished dish',
      stats: [['48h', 'dough rest'], ['430°', 'stone heat'], ['06', 'signature pies']],
    },
    featureTitle: 'Explore our products',
    featured: ['deep-dish', 'cheese-pull', 'garden-tacos', 'silk-road-pasta'],
    features: sharedFeatures,
    quote: 'The crust has that tiny crackle, then the chew, then the bright tomato. Exactly what pizza should be.',
    author: 'Rachel Baker',
  },
  'home-4': {
    key: 'home-4',
    frame: 'Home-4',
    path: '/home-4',
    layout: 'red-burger',
    theme: {
      accent: '#ffc327',
      accent2: '#111111',
      surface: '#ffffff',
      ink: '#111111',
      hero: '#c40f18',
      heroText: '#ffffff',
      card: '#ffffff',
    },
    eyebrow: 'Irresistibly hot',
    title: 'Hot spicy chicken burger.',
    lead: 'A full-red food-first hero with a giant burger, yellow handwritten details and straight-to-the-point ordering.',
    price: '$5',
    primary: 'Order now',
    secondary: 'Today’s special',
    heroImage: '/assets/burger.webp',
    heroAlt: 'A hot spicy chicken burger',
    alternate: {
      eyebrow: 'The evening table',
      title: 'Fire, season and quiet confidence.',
      lead: 'A composed menu led by the market and finished over flame.',
      price: '$38',
      image: '/assets/grilled-chicken.webp',
      alt: 'Restaurant grill plate',
    },
    story: {
      eyebrow: 'From the pass',
      title: 'Ingredients first, gestures second.',
      body: 'Our menu moves with the farms around us. Familiar dishes arrive with sharper herbs, deeper stocks and the confidence to stay simple.',
      image: '/assets/chef.webp',
      alt: 'Restaurant chef at the pass',
      stats: [['12', 'local farms'], ['04', 'seasonal menus'], ['1985', 'opened']],
    },
    featureTitle: 'From today’s menu',
    featured: ['flame-grilled', 'silk-road-pasta', 'garden-tacos', 'cheese-pull'],
    features: [
      ['Season-led', 'A concise menu that changes whenever the market does.'],
      ['Open kitchen', 'See each plate move from fire to finish.'],
      ['Warm service', 'Knowledgeable, relaxed and always nearby.'],
    ],
    quote: 'The rare dining room that feels special without ever becoming stiff. Every plate has a clear point of view.',
    author: 'Noah Williams',
  },
  'home-5': {
    key: 'home-5',
    frame: 'Home-5',
    path: '/home-5',
    layout: 'tastenest-original',
    theme: {
      accent: '#f41f4a',
      accent2: '#f5c229',
      surface: '#f7efe6',
      ink: '#1b1a1a',
      hero: '#111315',
      heroText: '#ffffff',
      card: '#ffffff',
    },
    lead: 'The original TasteNest homepage: dark ingredient hero, bold fast-food typography and the full motion treatment.',
    heroImage: '/assets/hero-ingredients.webp',
  },
  'home-6': {
    key: 'home-6',
    frame: 'Home-6',
    path: '/home-6',
    layout: 'pizza-red',
    theme: {
      accent: '#ffc137',
      accent2: '#f52d4b',
      surface: '#fff6d8',
      ink: '#191615',
      hero: '#e92d2d',
      heroText: '#ffffff',
      card: '#ffffff',
    },
    eyebrow: 'Start Your Order Just Only $25.00',
    title: 'Awesome Delicious Pizza',
    lead: 'A poster-bright red pizza page with enormous type, golden product tiles and a playful editorial rhythm.',
    price: '$22',
    primary: 'Order Now',
    secondary: 'Explore products',
    heroImage: '/assets/cheese-pizza.webp',
    heroAlt: 'A cheese pizza with a dramatic pull',
    alternate: {
      eyebrow: 'Crunch break',
      title: 'Fries deserve the spotlight.',
      lead: 'Skin-on, double cooked and showered with our tangy spice dust.',
      price: '$8',
      image: '/assets/fries.webp',
      alt: 'A generous serving of crisp fries',
    },
    story: {
      eyebrow: 'Fast without shortcuts',
      title: 'Real cooks. Real ingredients. Really quick.',
      body: 'Smart prep and a focused menu let us move quickly without pre-cooking the good part.',
      image: '/assets/food-table.webp',
      alt: 'Colourful fast-food dishes ready to share',
      stats: [['30m', 'delivery goal'], ['04', 'easy steps'], ['100%', 'cooked fresh']],
    },
    featureTitle: 'Pick your happy',
    featured: ['smash-stack', 'chicken-crunch', 'garden-tacos', 'deep-dish'],
    features: sharedFeatures,
    quote: 'Bright, quick and genuinely delicious. It is the easiest group-order decision we make all week.',
    author: 'Maya Foster',
  },
  'home-7': {
    key: 'home-7',
    frame: 'Home-7',
    path: '/home-7',
    layout: 'pink-chicken',
    theme: {
      accent: '#f52e50',
      accent2: '#ffe13c',
      surface: '#fffafa',
      ink: '#222023',
      hero: '#f9e7e8',
      heroText: '#222023',
      card: '#ffffff',
    },
    eyebrow: 'Fresh food, delivered with joy',
    title: 'Enjoy Our Delicious Meal',
    lead: 'A pale-pink chicken hero, red category carousel and sunlit highlights made for quick, happy ordering.',
    price: '$18',
    primary: 'Enjoy our meal',
    secondary: 'Shop best sellers',
    heroImage: '/assets/grilled-chicken.webp',
    heroAlt: 'A roasted chicken plate with bright sides',
    alternate: {
      eyebrow: 'Wok, smoke, repeat',
      title: 'Silky noodles after midnight.',
      lead: 'Toasted aromatics, chilli butter and parmesan for the late shift.',
      price: '$20',
      image: '/assets/pasta.webp',
      alt: 'Rich pasta finished with fresh herbs',
    },
    story: {
      eyebrow: 'One city, many cravings',
      title: 'Street-food energy under one roof.',
      body: 'We borrow the pulse, smoke and generous seasoning of favourite night markets without flattening what makes each dish distinct.',
      image: '/assets/food-table.webp',
      alt: 'Shared table of global dishes',
      stats: [['09', 'city influences'], ['01am', 'late close'], ['14', 'share plates']],
    },
    featureTitle: 'Tonight’s line-up',
    featured: ['garden-tacos', 'silk-road-pasta', 'chicken-crunch', 'flame-grilled'],
    features: [
      ['Open late', 'A full hot menu long after the sensible kitchens close.'],
      ['Share freely', 'Plates designed to land in the middle of the table.'],
      ['Turn it up', 'DJs, open flame and a room with a pulse.'],
    ],
    quote: 'It feels like four brilliant food stalls sharing one very good playlist.',
    author: 'Leo Martinez',
  },
  'home-8': {
    key: 'home-8',
    frame: 'Home-8',
    path: '/home-8',
    layout: 'white-burger',
    theme: {
      accent: '#f33459',
      accent2: '#159a55',
      surface: '#ffffff',
      ink: '#171717',
      hero: '#ffffff',
      heroText: '#171717',
      card: '#ffffff',
    },
    eyebrow: 'Fresh from the grill',
    title: 'Grilled beef burger.',
    lead: 'A crisp, ultra-clean burger composition with floating accents, circular offers and fresh pink product panels.',
    price: '$17',
    primary: 'Order grilled burger',
    secondary: 'Browse fresh products',
    heroImage: '/assets/burger.webp',
    heroAlt: 'A grilled beef burger with fresh toppings',
    alternate: {
      eyebrow: 'From the stone',
      title: 'One more slice for the table.',
      lead: 'Slow-fermented dough, sweet tomato and blistered mozzarella.',
      price: '$22',
      image: '/assets/pizza.webp',
      alt: 'Rustic stone-baked pizza',
    },
    story: {
      eyebrow: 'Come as you are',
      title: 'A table should get louder as dinner goes on.',
      body: 'Bowls arrive for passing, pizza lands already sliced and nobody minds if you ask for more bread.',
      image: '/assets/cheese-pizza.webp',
      alt: 'Cheesy pizza made for sharing',
      stats: [['48h', 'dough ferment'], ['07', 'fresh pastas'], ['∞', 'warm welcomes']],
    },
    featureTitle: 'La tavola',
    featured: ['silk-road-pasta', 'cheese-pull', 'deep-dish', 'flame-grilled'],
    features: [
      ['Fresh pasta', 'Rolled, cut and cooked in the same kitchen every day.'],
      ['Long ferment', 'Better texture, deeper flavour and crisp blistered edges.'],
      ['For sharing', 'Generous bowls and bottles made for the whole table.'],
    ],
    quote: 'The kind of place where lunch becomes dinner and nobody is in a hurry to leave.',
    author: 'Sofia Romano',
  },
  'home-9': {
    key: 'home-9',
    frame: 'Home-9',
    path: '/home-9',
    layout: 'aqua-feast',
    theme: {
      accent: '#f52e4c',
      accent2: '#2daa68',
      surface: '#edf8f7',
      ink: '#17262a',
      hero: '#edf8f7',
      heroText: '#ffffff',
      card: '#ffffff',
    },
    eyebrow: 'Food made for the moment',
    title: 'The perfect place for an unforgettable meal.',
    lead: 'A warm food-photography opening, pale-aqua best sellers and a red fresh-bites strip with restaurant polish.',
    price: '$24',
    primary: 'Order the perfect spread',
    secondary: 'See best sellers',
    heroImage: '/assets/salad-colorful.webp',
    heroAlt: 'A colourful spread of shared restaurant dishes',
    alternate: {
      eyebrow: 'The generous table',
      title: 'Good food loves good company.',
      lead: 'A colourful spread designed for easy, abundant sharing.',
      price: '$32',
      image: '/assets/tacos.webp',
      alt: 'Fresh vegetable-filled tacos made for sharing',
    },
    story: {
      eyebrow: 'Market to plate',
      title: 'Produce with a first name and a postcode.',
      body: 'We buy close, write the menu late and let the day’s best vegetables decide what happens next.',
      image: '/assets/grilled-chicken.webp',
      alt: 'Balanced grilled plate with vegetables',
      stats: [['12mi', 'average sourcing'], ['70%', 'plant-led menu'], ['0', 'hidden additives']],
    },
    featureTitle: 'Feel-good favourites',
    featured: ['garden-tacos', 'flame-grilled', 'silk-road-pasta', 'deep-dish'],
    features: [
      ['Market-led', 'Peak-season produce, bought close and used completely.'],
      ['Balanced', 'Bright vegetables, satisfying protein and joyful sauces.'],
      ['Low waste', 'Smarter prep, smaller footprints and compostable delivery.'],
    ],
    quote: 'Food that makes you feel looked after, not lectured. The sauces are exceptional.',
    author: 'Aisha Green',
  },
  'home-10': {
    key: 'home-10',
    frame: 'Home-10',
    path: '/home-10',
    layout: 'dark-teal',
    theme: {
      accent: '#c78345',
      accent2: '#9dad7e',
      surface: '#f3e6d4',
      ink: '#102121',
      hero: '#071617',
      heroText: '#f3e6d4',
      card: '#fffaf0',
    },
    eyebrow: 'An evening worth savouring',
    title: 'Reserve your table.',
    lead: 'A quiet, cinematic dark-teal dining room with brass accents, considered service and a menu led by the season.',
    price: '$38',
    primary: 'Reserve your table',
    secondary: 'Meet the kitchen',
    heroImage: '/assets/restaurant-dark.webp',
    heroAlt: 'A cinematic dark restaurant dining room',
    alternate: {
      eyebrow: 'Double trouble',
      title: 'The midnight smash stack.',
      lead: 'Two crisp-edged patties, molten cheese and a side of fries.',
      price: '$21',
      image: '/assets/burger-fries.webp',
      alt: 'Late-night burger and fries',
    },
    story: {
      eyebrow: 'Built around the fire',
      title: 'Live flame, loud flavour, zero hiding places.',
      body: 'Our open grill sits in the centre of the room. Every hiss, flare and final brush of butter is part of dinner.',
      image: '/assets/chef.webp',
      alt: 'Chef working in a dark restaurant kitchen',
      stats: [['900°', 'open flame'], ['06', 'house rubs'], ['02am', 'weekend close']],
    },
    featureTitle: 'From the fire',
    featured: ['flame-grilled', 'smash-stack', 'chicken-crunch', 'firehouse-burger'],
    features: [
      ['Live fire', 'Oak, charcoal and cooks who know when to leave it alone.'],
      ['Late tables', 'Full dinner service until two on Friday and Saturday.'],
      ['Big sound', 'Resident selectors and a room designed to hum.'],
    ],
    quote: 'Dark room, bright plates and the best char on a piece of chicken I have had all year.',
    author: 'Dylan Brooks',
  },
  'home-coffee': {
    key: 'home-coffee',
    frame: 'Home coffee',
    path: '/home-coffee',
    layout: 'coffee-house',
    theme: {
      accent: '#bf6f3f',
      accent2: '#65734b',
      surface: '#efe4d2',
      ink: '#33251e',
      hero: '#3c2921',
      heroText: '#fff9ee',
      card: '#f8f0e3',
    },
    eyebrow: 'Roasted close, poured slow',
    title: 'Coffee for the unhurried.',
    lead: 'A tactile neighbourhood coffee-house layout with warm grain, soft corners and an all-day brunch table.',
    price: '$4.50',
    primary: 'Order your usual',
    secondary: 'Explore the roast',
    heroImage: '/assets/coffee-dark.webp',
    heroAlt: 'Coffee being poured in a dark atmospheric cafe',
    alternate: {
      eyebrow: 'Brunch runs all day',
      title: 'Stay for one more plate.',
      lead: 'Bright, generous brunch food from opening until close.',
      price: '$16',
      image: '/assets/tacos.webp',
      alt: 'Fresh cafe brunch plate',
    },
    story: {
      eyebrow: 'Behind the bar',
      title: 'Small-batch coffee, big-table hospitality.',
      body: 'We roast in short runs, dial in throughout the day and keep enough room at the table for laptops, prams and long conversations.',
      image: '/assets/chef.webp',
      alt: 'Cafe chef presenting a fresh plate',
      stats: [['04', 'single origins'], ['07am', 'doors open'], ['12', 'brunch plates']],
    },
    featureTitle: 'Coffee & company',
    featured: ['garden-tacos', 'silk-road-pasta', 'firehouse-burger', 'cheese-pull'],
    features: [
      ['Roasted nearby', 'Fresh small-batch coffee with a transparent supply chain.'],
      ['All-day brunch', 'Real breakfast at noon and lunch whenever you need it.'],
      ['Stay awhile', 'Comfortable corners, kind service and another pour.'],
    ],
    quote: 'A genuinely lovely place to lose an hour. Excellent coffee, even better people.',
    author: 'June Parker',
  },
}

export const screenOrder = [
  'home-1',
  'home-2',
  'home-3',
  'home-4',
  'home-5',
  'home-6',
  'home-7',
  'home-8',
  'home-9',
  'home-10',
  'home-coffee',
]

export const purchaseFilters = ['All', 'Bold', 'Warm', 'Dark', 'Fresh']

export const purchaseGroups = {
  'home-1': 'Dark',
  'home-2': 'Bold',
  'home-3': 'Bold',
  'home-4': 'Warm',
  'home-5': 'Dark',
  'home-6': 'Bold',
  'home-7': 'Warm',
  'home-8': 'Warm',
  'home-9': 'Fresh',
  'home-10': 'Dark',
  'home-coffee': 'Warm',
}
